# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 01:00
from __future__ import unicode_literals

import caching.base
from django.db import migrations, models
import django.db.models.deletion
import source.jobs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_live', models.BooleanField(default=True, help_text='Job will display if this is checked and dates are within proper range', verbose_name='Display on site')),
                ('name', models.CharField(max_length=128, verbose_name='Job name')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('listing_start_date', models.DateField(default=source.jobs.models.get_today)),
                ('listing_end_date', models.DateField(default=source.jobs.models.get_today_plus_30)),
                ('tweeted_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=128, verbose_name='Contact name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Contact email')),
                ('location', models.CharField(blank=True, max_length=128, verbose_name='Job location')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Organization')),
            ],
            options={
                'ordering': ('organization', 'slug'),
            },
            bases=(caching.base.CachingMixin, models.Model),
        ),
    ]
