# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-06 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import source.jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-listing_end_date', 'organization', 'slug')},
        ),
        migrations.AlterField(
            model_name='job',
            name='listing_end_date',
            field=models.DateField(default=source.jobs.models.get_today_plus_30, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='listing_start_date',
            field=models.DateField(default=source.jobs.models.get_today, verbose_name='Start date'),
        ),
    ]
