# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-13 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20160128_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Most recent featured article appears at top of homepage', verbose_name='Featured article'),
        ),
    ]
