# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-06 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_is_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': 'pubdate', 'ordering': ('-pubdate', 'title')},
        ),
        migrations.AddField(
            model_name='article',
            name='lead_image_has_border',
            field=models.BooleanField(default=False, verbose_name='Put a border on lead image'),
        ),
    ]
