# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2022-02-21 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_articleblock_image_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_alt_text',
            field=models.TextField(blank=True),
        ),
    ]
