# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 01:00
from __future__ import unicode_literals

import caching.base
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_live', models.BooleanField(default=True, verbose_name='Display on site')),
                ('show_in_lists', models.BooleanField(default=True, verbose_name='Show on Organization list page')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email address')),
                ('twitter_username', models.CharField(blank=True, max_length=32)),
                ('github_username', models.CharField(blank=True, max_length=32)),
                ('github_repos_num', models.PositiveIntegerField(blank=True, null=True)),
                ('github_gists_num', models.PositiveIntegerField(blank=True, null=True)),
                ('homepage', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('state', models.CharField(blank=True, max_length=32)),
                ('country', models.CharField(blank=True, help_text='Only necessary if outside the U.S.', max_length=32)),
                ('logo', sorl.thumbnail.fields.ImageField(blank=True, help_text='Resized to fit 200x50 box in template', null=True, upload_to='img/uploads/org_logos')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(caching.base.CachingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrganizationLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Organization')),
            ],
            options={
                'verbose_name': 'Organization Link',
                'ordering': ('organization', 'name'),
            },
            bases=(caching.base.CachingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_live', models.BooleanField(default=True, verbose_name='Display on site')),
                ('show_in_lists', models.BooleanField(default=True, verbose_name='Show on People list page')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email address')),
                ('twitter_username', models.CharField(blank=True, max_length=32)),
                ('twitter_bio', models.TextField(blank=True)),
                ('twitter_profile_image_url', models.URLField(blank=True)),
                ('github_username', models.CharField(blank=True, max_length=32)),
                ('github_repos_num', models.PositiveIntegerField(blank=True, null=True)),
                ('github_gists_num', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, verbose_name='Bio')),
                ('organizations', models.ManyToManyField(blank=True, to='people.Organization')),
            ],
            options={
                'verbose_name_plural': 'People',
                'ordering': ('last_name', 'first_name'),
            },
            bases=(caching.base.CachingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PersonLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person')),
            ],
            options={
                'verbose_name': 'Person Link',
                'ordering': ('person', 'name'),
            },
            bases=(caching.base.CachingMixin, models.Model),
        ),
    ]
