# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-13 17:55
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='img/uploads/person_photos'),
        ),
    ]
