# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-06 22:15
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_organizationadmin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationadmin',
            options={'ordering': ('organization', 'email'), 'verbose_name': 'Organization Admin', 'verbose_name_plural': 'Organization Admins - These email addresses will be able to log in and manage job postings for this organization'},
        ),
        migrations.AlterModelOptions(
            name='personlink',
            options={'ordering': ('person', 'name'), 'verbose_name': 'Person Link', 'verbose_name_plural': 'Person Links - The first item will be linked as "Visit Website" in author bios'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Resized to fit 300x200 box in template', null=True, upload_to='img/uploads/org_logos'),
        ),
    ]
