# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-23 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='author_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='author_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='guide',
            name='author_photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='img/uploads/guide_author_images'),
        ),
        migrations.AddField(
            model_name='guidearticle',
            name='external_author_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='guidearticle',
            name='external_organization_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
