# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-06 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_auto_20170123_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='author_name',
            field=models.CharField(blank=True, help_text="This field accepts HTML, so you can wrap an author's name in a link.", max_length=128),
        ),
    ]
