# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-13 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code', '0002_auto_20160128_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='demo_site',
            field=models.URLField(blank=True, verbose_name='Demo site'),
        ),
        migrations.AddField(
            model_name='code',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='A selection of featured projects appears on the Code landing page', verbose_name='Featured repo'),
        ),
        migrations.AlterField(
            model_name='code',
            name='url',
            field=models.URLField(verbose_name='Repository URL'),
        ),
    ]
