# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-19 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code', '0004_auto_20170117_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='grouping',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
