# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-23 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code', '0005_code_grouping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='grouping',
            field=models.CharField(blank=True, help_text='The primary category where this repo will be grouped on the Code page.', max_length=64),
        ),
    ]
